### ISSUE TITLE
Feb 28th, 2015 Debrief 

### ISSUE THREAD

**Issue by blakmatrix** [nodeschool/seattle#10]
Mentors & Students: Please comment on how the event went-- What went well, what could go better, any flags, how the workshoppers went, etc. so we can make future events better and more accessible to all.

Thanks in advance!

**Comment by rebeccapeltz** [comment]
Great meet up.  It was an opportunity to both learn node and speak with others with similar interest.  The mentors are execcellent - enthusiastic and knowledgeable.  I hope I can attend more of the bide school events.

**Comment by prabhupr70** [comment]
Great event, I learned a lot. Thanks for organizing this. Thanks to everybody who helped
If one can be organized on east-side that would be a great help
Suggestion: Everybody who worked on same practice session, if they can work together that might improve the productivity :)

**Comment by susanev** [comment]
Yes, I agree -- maybe it would be nice to have labeled table groups for
each tutorial, and people working on that tutorial can sit in that section;
and since there was sooo many volunteers maybe have one volunteer
designated/seated at each section.

On Sun, Mar 1, 2015 at 10:11 PM, prabhupr70 <notifications@github.com>
wrote:

> Great event, I learned a lot. Thanks for organizing this. Thanks to
> everybody who helped
> If one can be organized on east-side that would be a great help
> Suggestion: Everybody who worked on same practice session, if they can
> work together that might improve the productivity :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodeschool/seattle/issues/10#issuecomment-76663207>.
>



-- 
susan ev(ans)
Computer Science Instructor | Cleveland High School
User Experience Designer | UW LiY! <http://advance.washington.edu/liy/>

**Comment by louisnk** [comment]
I like the ideas! I agree that it could be useful to have people organize by general skill level and work through the tutorials together. My only reservation about that would be seeing one person "lead" the table/group, and not give others the chance to figure it out for themselves.

**Comment by daveskull81** [comment]
I thought the event went well overall. I feel like I learned a lot and I know it was very helpful for me. I like the idea of mentors sticking to one area. Since there was so many of them it would be great if one or two stuck to certain tables and helped out those people specifically. It could help people to get the courage to ask questions and open up the group to engage with the mentors.

**Comment by ptressel** [comment]
@louisnk, I think the "sit at one table" idea doesn't intend to have people work in unison on the tutorials, but rather to be able to chat with each other about them at need.  Also maybe a bit less intimidating for folks doing the beginning tutorials than if there folks discussing advanced stuff that sounds like line noise.  ;-)  Would also allow mentors to sort themselves out by familiarity with the tutorial topics.

**Comment by strugee** [comment]
Yeah, the tables thing might be a good idea. As a mentor, it seemed like people were mostly getting it, but I don't know if that mirrors what other people saw, as I wasn't really sure how to engage with participants without jolting them out of "the zone". Maybe we need to encourage questions more the beginning?

Also, it would be nice if we could give plugs to SeattleJS and the Node.js Seattle user group.

**Comment by sjbenner** [comment]
With respect to mentoring, I agree, it was hard to tell if someone wanted or needed help.  In almost every case, when I asked if someone needed help, they had questions.  Next time lets "suggest" some methods for signaling that an individual needs help.  We could use something like the red/green cards common in Brazilian style Rodizio restaurants.  Learners could flip the card to green when they have questions and to red if they're in the zone.  I know that we had a gitter discussion but I don't know who, if anyone, was monitoring it.

The table ideas people have been suggesting here are interesting.  I had been thinking that it might help to go over each exercise after people have had time to work on them.  I'm not sure how to do that without interrupting those in the zone.  Maybe we could break every 20/30/45 minutes and gather around the projector or whiteboard and open up to the floor for general questions and discussion.

Overall, I thought the meetup went well.  Thanks to the hosts!

**Comment by blakmatrix** [comment]
Thanks for all the Feedback All, It is so great to have people care so much about the community, Lets keep the momentum going!
