### ISSUE TITLE
Join the Seattle NodeSchool team

### ISSUE THREAD

**Issue by sethvincent** [nodeschool/seattle#11]
If you'd like to help organize events & volunteer with Seattle NodeSchool leave a comment here and we'll add you to the github organization.

We do all the organizing for events in the issues queue of that repository, so that's the best way to get involved if you're interested in volunteering.

**Comment by ryanmurakami** [comment]
I'd like to volunteer!

**Comment by strugee** [comment]
I'm interested in helping more in the future (although I've already been added to the organization).

**Comment by sethvincent** [comment]
Cool. @ryanmurakami I've added you to the seattle nodeschool team.

Thanks @strugee!

**Comment by ryanmurakami** [comment]
Thanks @sethvincent!

**Comment by blakmatrix** [comment]
Closing this out, as a note, I don't feel like this was that effective at getting people added to the organization, maybe next time we should push the gitter, and add people from there... though, it might get to hard to keep up with it. if anyone has some thoughts on getting more people added to the seattle nodeschool open up a new issue and lets discuss!
