### ISSUE TITLE
March 28th, 2015 Call for Mentors

### ISSUE THREAD

**Issue by blakmatrix** [nodeschool/seattle#13]
We will need about 20 mentors for this event. If you can commit to March 28th, 2015 from 1-5pm let us know. I will update this list as we get more mentors.

- [x] Farrin Reid @blakmatrix / Organizer
- [x] Seth Vincent @sethvincent
- [x] Josh Benner @libreninja 
- [x] Louis K @louisnk 
- [x] Adrienne Kerr @jungledre  
- [x] Ryan Lewis @ryanmurakami 
- [x] Tyler Iguchi @tyleriguchi   
- [x] Melanie Davis @mahzaib 
- [x] Brian Shourd @brianshourd 
- [ ] ~~Sanda Htyte @bksanda~~
- [x] Jordan Ball @cjordanball 
- [ ] ~~Claire Lyles @clairelyles~~ 
- [x] Rob Middleton @Rob-ot   
- [x] Alex Jordan @strugee 
- [ ] ?  
- [ ] ? 
- [ ] ? 
- [ ] ? 
- [ ] ? 
- [ ] ? 
- [ ] ? 
- [ ] ?

**Comment by sjbenner** [comment]
Count me in.

**Comment by louisnk** [comment]
Me too

**Comment by jungledre** [comment]
ditto

**Comment by ryanmurakami** [comment]
I'd like to mentor!

**Comment by tyleriguchi** [comment]
I'd like to get in on this

**Comment by mahzaib** [comment]
I am available to mentor for this event.

**Comment by brianshourd** [comment]
I'd love to mentor

**Comment by bksanda** [comment]
I'll be a mentor :)

**Comment by cjordanball** [comment]
I'd be happy to!

**Comment by clairelyles** [comment]
I'd be happy to mentor!

**Comment by blakmatrix** [comment]
Hey all,

I just want to thank you all for signing up to be a mentor for tomorrows event, I am super pumped about it and the lives we will touch. Please try and arrive 30 minutes early (12:30pm) to help set up and prep for the 1pm arrivals.

Also, the weather looks like it'll be mostly cloudy with 10% chance of precipitation... so we might have a larger showing than in February (when it was sunny and clear skies)... If you all can **promote** https://twitter.com/nodeschool_sea/status/581599766469058560 and maybe recruit a few more Mentors that would be super helpful!

**Comment by blakmatrix** [comment]
# Location

Where: 1633 Westlake Avenue North, Suite 400, Seattle, WA 98109
When: 12:30pm-4(5 latest)pm March 28th, 2015
Parking: If guest parking is taken, there is paid parking down 8th Avenue North, in the SRM building, located at 1505 Westlake Ave North (where Westlake Ave. N. and 8th Ave. N. meet)
Arrival: There are two entrances 1633 Westlake Avenue North or 1616 8th Avenue North, If you are driving, use the 8th Avenue North garage entrance (it is a brick building with the parking entrance unmarked on the south end of the building) for guest parking if available.
If you are arriving by taxi or public transportation, you can enter the building from either entrance, but the 8th Ave. N. entrance is more suitable for passenger load/unload.

**Comment by Rob-ot** [comment]
I'm about 95% sure I can make it. I'll see you all tomorrow!

**Comment by strugee** [comment]
@blakmatrix I assume you still needed more mentors, right? I should be there tomorrow.

**Comment by clairelyles** [comment]
Rats! I hate to do this last minute, but I'm unable to make it to today's event due to another conflict. I'll see you guys at the next event. Best of luck!

**Comment by blakmatrix** [comment]
Thanks to all who signed up! see you all soon!

**Comment by blakmatrix** [comment]
/all thanks for mentoring at the event today! If you wouldn't mind please take a few moments to debrief here https://github.com/nodeschool/seattle/issues/26
