### ISSUE TITLE
Seattle NodeSchool #3 March 28th, 2015

### ISSUE THREAD

**Issue by blakmatrix** [nodeschool/seattle#14]
Hi all,

We've secured space on March 28th, 2015 thanks to our gracious IMS Health. It will be at the same location as the last one (1633 Westlake Ave N Ste 400, Seattle, WA, USA) .

Ways to help:
- [x] finding a space
- [x] being a mentor at the event ([signup here](https://github.com/nodeschool/seattle/issues/13))
- [x] recruiting other mentors for the event
- [x] finding a sponsor to cover snacks & drinks
- [x] promoting the event
- [x] Announce event

**Comment by louisnk** [comment]
@blakmatrix as far as including/inviting other groups (promotion, etc) - have you reached out to any other meetup groups? Girl Develop it, Seattle Node, ___________?

Beyond that, have you contacted any reporter/blogger type people, to try to reach a broader audience?

**Comment by blakmatrix** [comment]
@louisnk I have asked a mentor here to reach out to the Geek Girl Carrots group that she organizes other than that, if you have the contacts feel free to reach out, we need the outreach :)
Other than that just Word of Mouth :) I figure reporters would be good once we get the structure and metting running more frequently and smoothly, I'm afraid geekwire will pop in and we'll just be overwhelmed and not ready for the event itself.

**Comment by louisnk** [comment]
@blakmatrix sweet. Is Geek Girl Carrots involved with Girl Develop it? I feel like it's a sub group or something, but definitely having them blast it to their meetup list could be good.

I'll make a list of the most common meetup groups, float it on here, and see who we want to contact, and when. There are probably tons of groups that we could coordinate with and draw attendees from. At the same time, we probably need to do it slowly so we don't explode.

I think you're right as far as reporters go, although we could start compiling a list of publications to contact as well. More local/small-scale might be a good place to start to gauge interest.

**Comment by blakmatrix** [comment]
Thanks everyone!

**Comment by blakmatrix** [comment]
https://github.com/nodeschool/seattle/issues/26
