### ISSUE TITLE
Update Seattle NodeSchool site for March 28th, 2015 event

### ISSUE THREAD

**Issue by blakmatrix** [nodeschool/seattle#15]
We need to update the Nodeschool site (http://nodeschool.io/seattle/) to reflect the new event, Feel free to submit a PR!

**Comment by blakmatrix** [comment]
Also would be great to add

```html
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-60703999-1', 'auto');
  ga('send', 'pageview');

</script>
```

**Comment by sjbenner** [comment]
I'm ready to make a pull request. Though we don't have a direct link to the next event as we did previously.  Is it ok to link to the meetup group page for now or should this wait until we officially schedule the event on meetup.com?

##### direct event link
```html
<p><a href="http://www.meetup.com/Seattle-NodeSchool/events/220020622/" class="button">RSVP for the Feb. 28 workshop</a></p>
```

##### meetup group page link
```html
<p><a href="http://www.meetup.com/Seattle-NodeSchool/" class="button">RSVP for the Mar. 28 workshop</a></p>
```

**Comment by sethvincent** [comment]
@sjbenner: I went ahead and set up the event on meetup, here's the link: http://www.meetup.com/Seattle-NodeSchool/events/221135698/

@blakmatrix: feel free to edit details on the meetup event.

**Comment by blakmatrix** [comment]
@sethvincent ROfl http://www.meetup.com/Seattle-NodeSchool/events/221135713/ saved it as a draft

**Comment by sethvincent** [comment]
woopsy!

**Comment by blakmatrix** [comment]
Its fine. I deleted draft haha :) @sjbenner use Seths, I set it to start rsvping 10 days before the event, so next tuesday.

**Comment by sethvincent** [comment]
oh good idea about the rsvp timing

**Comment by sjbenner** [comment]
done!

The title of the event says the 28th but it looks like it's scheduled for the 27th.

**Comment by sethvincent** [comment]
fixed!

**Comment by sjbenner** [comment]
see pull request #17
