### ISSUE TITLE
Announce the Next meetup (3/28) by 5pm PST

### ISSUE THREAD

**Issue by blakmatrix** [nodeschool/seattle#18]
Hi all the current meetup is here http://www.meetup.com/Seattle-NodeSchool/events/221135698/ , it hasn't been announced but RSVPs are now open.

I'd like to announce it by 5pm... **BUT** I wanted to know if anyone had suggestions for the copy of the meetup (*the description*) and or the message that goes out.

**Comment by sjbenner** [comment]
I think the copy is good.

I know that there were a few people at the last event that came to work on things 'node related' but 'out of scope' with respect to the nodeschool exercises.  I'm not opposed to these self directed nodeschool activities but do we have any policies/rules etc... for people that come and ask for help with a personal or work project?  Do we need to say anything about that in the event description?

**Comment by blakmatrix** [comment]
It's great that we have people wanting to hang out, my only concern though is for those that would actually like to use the event to learn node, we want to make sure those people get the chance to attend... @louisnk and I have been working on getting a bi-weekly NodeSchool frequency going, and for that kind of frequency that shouldn't be a problem, heck I'd encourage it as long as they are adhering to the CoC linked below, and not putting anybody out. I've heard there is an average of 60% attendance rate, they wont be hurting anyone except maybe those that wish to signup on the list, so maybe if we see them regularly we can ask them to come to the next one but maybe leave there spots open for others on meetup.com

@sjbenner the only rules are [the code of conduct](https://github.com/nodeschool/seattle/blob/gh-pages/codeofconduct.md)

**Comment by louisnk** [comment]
I agree, I think the copy is totally good.

What if we make an announcement asking everyone who's just working on their own stuff/looking for help with more advanced node problems to gather at their own table, so mentors aren't distracting other people? I think it should be encouraged for them to come, it just builds the community. 

Like people mentioned in the planning thread, attendance shouldn't matter so much here. We could always up the RSVP limit on Meetup to accommodate the no-shows, if it seems like a problem.

As for the frequency, hopefully in April there will be two events, with one on a weekday evening.

**Comment by blakmatrix** [comment]
Done!
