### ISSUE TITLE
Unsble to run anything in node.js

### ISSUE THREAD

**Issue by catearth** [nodeschool/seattle#2]
Used nodejs.org to install for Windows 64-bit.
OS Windows 7, Firefox
Cannot Run or Update anything:

>npm install -g javascripting learnyounode

getting "npm should be run outside of the node repl,in your normal shell."

Unsure what this means or how to correct.

**Comment by sethvincent** [comment]
I'm going to close this for now. Feel free to reopen it if there are continuing issues.
