### ISSUE TITLE
Seattle NodeSchool #4 April 7th, 2015

### ISSUE THREAD

**Issue by blakmatrix** [nodeschool/seattle#23]
Hi all,

We've secured space on April 7th, 2015 thanks to our gracious sponsor Moz in downtown Seattle.

Ways to help:
- [x] finding a space
- [ ] we will need a greeter for this event, some one that will send people up to the floor with a keycard and who can be a point of contact in case we have some late shows 
- [ ] Someone to take a few photos 
- [ ] being a mentor at the event ([signup here](https://github.com/nodeschool/seattle/issues/22))
- [ ] recruiting other mentors for the event
- [x] finding a sponsor to cover snacks & drinks
- [x] promoting the event
- [x] Announce event

**Comment by louisnk** [comment]
I'll try to hustle some other people into mentoring. Who doesn't love to learn, and help other people learn?!

**Comment by qayshp** [comment]
I can take "a few photos" but also plan to be learning at the event, since I'm new to node.

**Comment by blakmatrix** [comment]
@qayshp That'd be great. I deally I'm just thinking that if we can get a few people at the events taking photos and tweeting them @nodeschool_sea on twitter or something that should be fairly good as we want to eventually get a gallery together to show people what they can expect... at least as much as a picture can show ! :)

**Comment by qayshp** [comment]
Oh, I didn't even think of that. For tweeting and other social media, I can use my phone. If you want better, I can bring a DSLR too.

**Comment by louisnk** [comment]
I'll be mentoring, so I can use my DSLR to get some shots while people learn (or Seth could bring his again?), but you're right - Tweeting things will be even cooler!

@qayshp - don't take time out of your learning to take a bunch of photos :)

**Comment by blakmatrix** [comment]
https://github.com/nodeschool/seattle/issues/28

Thanks again everyone.
