### ISSUE TITLE
Late April Meetup

### ISSUE THREAD

**Issue by blakmatrix** [nodeschool/seattle#25]
Hey all,

I was hoping to get the discussion started here for a late April meetup.

**Comment by louisnk** [comment]
Yes. Do we need a host, or will IMS health be down to do it again? If not them, we need to start asking around now to get something locked down. I might be able to be more help with this coming very soon. I'll keep you posted.

**Comment by strugee** [comment]
Just to point out, April 25-26 is LinuxFest Northwest. I don't know how much of our demographic coincides with theirs, but surely _some_ people will be going there instead of NodeSchool (myself included). Just something to bear in mind. /me shrugs

**Comment by strugee** [comment]
Unless, of course, you didn't mean _that_ late in the month?

**Comment by sethvincent** [comment]
i'll also be at linuxfest northwest that weekend.

**Comment by blakmatrix** [comment]
I am planning on attending Linux fest as well, perhps we should shoot for early may, but for sure may 23rd as that is nodeschool international day

**Comment by blakmatrix** [comment]
I'm gonna close this as it seems that Linux fest is taking up late april
