### ISSUE TITLE
March 28th, 2015 NodeSchool Event Debrief

### ISSUE THREAD

**Issue by blakmatrix** [nodeschool/seattle#26]
Mentors & Students: Please comment on how this event went -- What went well? What could go better? Any flags, how did the workshoppers go?, etc.
We want to make future events better and more accessible to all, so your feed back is valuable.

Thanks in advance!

**Comment by blakmatrix** [comment]
I personally had a blast, I ended up working with a handful of people through some issues (windows environment variable crazyness, helping some beginners and advanced folks). I estimated that we had 10-12 mentors and ~50 nodeschool students (did anyone get a specific count)?

One thing I learned is that most people don't know about [`console.dir()`](https://developer.mozilla.org/en-US/docs/Web/API/Console/dir) which I usually find to be super-helpful when trying to inspect JavaScript types(objects, arrays, etc) via command-line code.

I also think that asking people to bring snacks for the group worked out really well this time.

Compared to the last NodeSchool event, the room seemed to be much more lively in the first half, I think this was attributed to the better introduction and explanation about mentors and encouragement to both not be afraid to ask questions and to keep it light and fun (I don't think I heard anyone "woo" though... we need to fix that :wink: ).

I feel like there is a lot of info wrangling we need to do near the beginning, the e-mail that I send out the day before the event seems to do a good job getting most people up on node, but things like our [twitter](https://twitter.com/nodeschool_sea), our [gitter](https://gitter.im/nodeschool/seattle), our [github repo](https://github.com/nodeschool/seattle/), [CoC](https://github.com/nodeschool/seattle/blob/gh-pages/codeofconduct.md), etc.-- we could do a better job connecting all of those for everyone

**Comment by rebeccapeltz** [comment]
Sorry I missed this - I really enjoyed the last meet up.

**Comment by cjordanball** [comment]
I had a great time.  I signed up to serve as a mentor, but this was the first of these events I had attended, so I wasn't particularly helpful, just trying to see how everything worked this time.  I plan to continue attending, and will make an effort to be more helpful in the future!

**Comment by louisnk** [comment]
I, too, had a great time! It was great to see lots of people pushing through stuff on their own, and collaborating a little bit to help one another through workshops without the help of mentors, necessarily. 

Also exciting to see lots of recent GA/CodeFellows graduates coming out to continue building their skills. Hopefully they all come back as mentors down the road :)

I think this may have been even more diverse than the last one, so sweet! I would love to hear from anyone about how we could improve this further?
