### ISSUE TITLE
Early May Meetup?

### ISSUE THREAD

**Issue by blakmatrix** [nodeschool/seattle#29]
I am just gauging this for now, but what would people think about an early may meetup? (given that we have to have on May 23rd for NodeSchool International day)

**Comment by chrisvariety** [comment]
Early may sounds good.

FYI May 23rd is Memorial Day Weekend here in the US, so I imagine *a lot* of people will be out of town...

**Comment by libreninja** [comment]
Sure.  Do we want to try midweek again?  Or line something up for the 2nd or 9th?

Do we have any sponsors interested in hosting?

I can reach out to the people at [Vitamin T](https://vitamintalent.com/).  They expressed interest in sponsoring food for us.  They provided marination mobile at the node.js meetup last night at Madrona.

**Comment by blakmatrix** [comment]
@libreninja Tune via @zerious has expressed some interest. Also we might be able to make something work through the connections I am setting up with GeneralAssembly (WeWork).

**Comment by louisnk** [comment]
I'll be in Cuba for the last 2 weeks of May, so I'll be unable to help out...
