### ISSUE TITLE
Next Seattle NodeSchool event

### ISSUE THREAD

**Issue by sethvincent** [nodeschool/seattle#3]
The next Seattle NodeSchool event could happen late January or early February.

Maybe February 7?

If you're interested in volunteering to help make it happen you can leave a message in this thread.

Things you could help with:

- [x] finding a space
- [x] being a mentor at the event
- [x] recruiting other mentors for the event
- [x] finding a sponsor to cover snacks & drinks
- [x] promoting the event

**Comment by sethvincent** [comment]
About the first event:

We had somewhere around half the RSVPs show up.

There was a challenge with wifi, specifically that it didn't work, but made it through by sharing flash drives with some workshops and sharing phone wifi hotspots.

**Comment by sethvincent** [comment]
Possible dates for the next event:

- Feb 7
- Feb 14
- Feb 28

These work for me anyway.

**Comment by blakmatrix** [comment]
I have some concerns about some folks not wanting to come out just because it is Valentines day, but I'm good for either of those date's as well.

**Comment by sethvincent** [comment]
Ha. Didn't even occur to me that Feb 14 is Valentine's. Good point.

**Comment by blakmatrix** [comment]
Another thing to discuss is timing, some of this might be dependent on the space we get or sponsor. I feel like if we were to shoot for a time, looking at others timing I see most starting at 10 am or after lunch around 1pm going for 3-4 hours afterwards. I'm good with either times. Just as a FYI, for the nodeschools that start in the afternoon, I've been seeing a practice by some chapters where they go and have a happy hour/dinner nearby to discuss how things went, what they liked, what can be done better - not sure if we would want to try something like this, but I feel like we should be mindful if we do take this approach, to not exclude anyone (i.e underage folks by going to a bar).

**Comment by blakmatrix** [comment]
As far as promotions, I was wanting to reach out to a few contacts this week, but I think we should at least get up the next on on meetup.com as TBA for either 14/28th (7th only if we get a sponsor good for that time). @sethvincent Do you know if the place we were at in December is usually available... I feel like we should have a couple default back up meeting places if reaching out to sponsors is uneventful.

#### "Reach out to a wider group of potential attendees to encourage a more diverse turnout"
In general, It sounded like meetup.com got us plenty of signups, but I'd like see us reach out to groups like "Women who code", "Girl Develop It (GDI)", maker/hacker groups (and potentially cross meetup group -- sorry I don't know the correct terminology), and other developer groups here in the Seattle area --At the heart of the Nodeschool community is reflective of the Node.js community which has always been open to anyone from beginners to experts.

**Comment by blakmatrix** [comment]
I've secured us some space at Appature/iMS health on the 28th!! It can hold 100 nodeschoolers easy.

**Comment by sethvincent** [comment]
Cool! Does all this info look correct?

February 28, 1-4 p.m.
at Appature
1633 Westlake Avenue North Suite 400, 
Seattle, WA 98109

**Comment by blakmatrix** [comment]
#7

**Comment by blakmatrix** [comment]
#6 is the event curriculum issue

**Comment by blakmatrix** [comment]
#10 is the Debrief of this successful event, Good Job all!
