### ISSUE TITLE
NodeSchool International Day - May 23rd, 2015 Call for Mentors

### ISSUE THREAD

**Issue by blakmatrix** [nodeschool/seattle#30]
We will need about 15-20 mentors for NodeSchool International Day (see #8 ). If you can commit to May 23rd, 2015 from 1-5pm let us know. I will update this list as we get more mentors.

- [x] Farrin Reid @blakmatrix / Organizer
- [ ] Keith Jia @keithjia
- [x] Seth Vincent @sethvincent  
- [x] Luke Stewart @LukeSwart 
- [x] Manu @manuisfunny 
- [x] Jordan Ball @cjordanball  
- [x] David Harris @RnbWd 
- [x] Joshua Hutt@huttj 
- [x] Stuart P. Bently @stuartpb 
- [ ] ? 
- [ ] ?
- [ ] ?
- [ ] ? 
- [ ] ?  
- [ ] ? 
- [ ] ? 
- [ ] ? 
- [ ] ? 
- [ ] ? 
- [ ] ? 
- [ ] ?

**Comment by louisnk** [comment]
Sadly I'm afraid this is going to be a tough weekend to recruit mentors, seeing as it's Memorial Day weekend. I'll be in Cuba though, so you'll have to make due without me.

**Comment by blakmatrix** [comment]
Hey everyone! This NodeSchool International day is shaping up to be a good one, we will need mor ementors than the 3 listed. @libreninja @chrisvariety @manuisfunny @joshgit @LukeSwart @cjordanball @jungledre @ryanmurakami @tyleriguchi @mahzaib @brianshourd (will you be IMS Health representative again?) @bksanda @Rob-ot @clairelyles @saasmath @pjbr @eugeniy @RnbWd  @eugeniy @housepage  @scottbrady @craigbeck @sjbenner

**Comment by LukeSwart** [comment]
I'll be around! Add me please :-)

**Comment by manuisfunny** [comment]
I can also make it.  Please add me.

**Comment by cjordanball** [comment]
Sign me up!


C. Jordan Ball III
2214 E. Highland Drive
Seattle, Washington 98112
(757) 425-6200
cjordanball@icloud.com

**Comment by RnbWd** [comment]
I would love to attend again!! What's the planned agenda?

**Comment by huttj** [comment]
I am game! Please add me.

**Comment by stuartpb** [comment]
I'll be there with my Chromebook in tow.

**Comment by strugee** [comment]
Note that this weekend is (CodeDay)[https://codeday.org/]. Might be a good opportunity for outreach, if you can get in touch with the organizers in time.

**Comment by blakmatrix** [comment]
@strugee would you like to make an announcement about it during the meetup?

**Comment by keithjia** [comment]
sorry guys, last min family stuff, can't make it this Sat. Hope you guys have a successful event.

**Comment by RnbWd** [comment]
Is it happening? What time? Sorry on my phone in car

**Comment by huttj** [comment]
Saturday, May 23, 2015
1:00 PM to 4:00 PM
IMS Health
1633 Westlake Ave N Ste 400, Seattle, WA

**Comment by RnbWd** [comment]
Sorry I'll be running 30 min late, but I can stay around to help past 4 if
needed.

**Comment by sethvincent** [comment]
video clips from today: https://www.youtube.com/playlist?list=PLtqV0D_WhsDkeaLIDMJ2mm288psaVY4IM

**Comment by strugee** [comment]
@blakmatrix shoot, sorry. Didn't check GitHub since I commented. School, and all that. :/

**Comment by daveskull81** [comment]
The videos are awesome. Thanks for sharing @sethvincent.
