### ISSUE TITLE
mini nodeschool at Code for Seattle's DiscoTech (part of the national day of civic hacking)

### ISSUE THREAD

**Issue by sethvincent** [nodeschool/seattle#31]
I'm planning on holding a mini nodeschool event as part of the upcoming DiscoTech event at Seattle City Hall on June 6.

More information about the larger event here: http://codeforseattle.org/discotech

It would be great to get a few volunteer mentors for the event. Other things look food, space, etc. are all taken care of.

We need probably only about 5 volunteers. Please sign up by leaving a comment.

**Comment by blakmatrix** [comment]
I'll help out, sounds fun!

**Comment by louisnk** [comment]
I'm in. I'll be freshly back from our nearest communist neighbor, so I'll be fully appreciative of the open civic opportunities

**Comment by libreninja** [comment]
Count me in.

**Comment by keithjia** [comment]
I could help.

**Comment by stuartpb** [comment]
The site needs to be updated - it's still saying the next event is May 23rd.

> I'm in. I'll be freshly back from our nearest communist neighbor

You mean [Fremont](http://en.wikipedia.org/wiki/Statue_of_Lenin,_Seattle)?

**Comment by louisnk** [comment]
Damn...this was Saturday. Turns out coming back from Communism takes some re-acclimation to western life. 

How did it go?

**Comment by blakmatrix** [comment]
I'm sorry guys I totally spaced this, been super busy with work and caring for my grandmother after her surgery.
