### ISSUE TITLE
Seattle NodeSchool International day Stickers (looking for sponsor)

### ISSUE THREAD

**Issue by blakmatrix** [nodeschool/seattle#32]
Hey everyone, I wanted to get some stickers for the upcoming NodeSchool International day. Does anyone have any ideas to get a quick turn around (10 days or so before the event) or sponsor ideas, or would your company want to sponsor these stickers in return for a plug at the event?

*Are you a sponsor? e-mail me at blakmatrix@gmail.com* 

# Details

**How Many?**: We will need about 100 for the event.
**Files**: Assets are here https://github.com/nodeschool/international-day/tree/2015/Stickers

In particular, this one should do the trick:

![https://github.com/nodeschool/international-day/blob/2015/Stickers/nodeschool-int-cutout.svg](http://hexb.in/hexagons/nodeschool-int.png)
(Note: we want to use https://github.com/nodeschool/international-day/blob/2015/Stickers/nodeschool-int-cutout.svg for the vendor, or the `ai` file where the assets are located...)

I was looking on stickermule, *it'd be nice to get some of these https://www.stickermule.com/marketplace/1502-nodeschool-dot-io for future events*, but in particular
at this vendor a 2x2 inch sticker (don't need larger ones) follows the following pricing scheme:

|count|price|savings|
|---:|---:|---:|
|50|$57|| 
|100|$68|Save 40%|
|200|$89|Save 61%|
|300|$108|Save 68%|
|500|$141|Save 75%|
|1,000|$215|Save 81%|
|2,000|$343|Save 85%|
|3,000|$459|Save 87%|
|5,000|$669|Save 88%|
|10,000|$1,133|Save 90%|

**Comment by willscott** [comment]
Can we get a seattle-color-theme nodeschool logo? :trophy:
I've gotten similar prices and pretty fast turnaround from http://www.standoutstickers.com/ as well.

**Comment by blakmatrix** [comment]
@willscott I'd like to do a seattle one... but I feel like we need a designer to seattl-ify our logo -- check out #9

**Comment by sethvincent** [comment]
@blakmatrix did you end up ordering international day stickers?

if not i'll do it today

**Comment by blakmatrix** [comment]
@sethvincent that would be awesome!

**Comment by sethvincent** [comment]
ordered!
