### ISSUE TITLE
Summer NodeSchool?

### ISSUE THREAD

**Issue by louisnk** [nodeschool/seattle#33]
Hey Seattle,

Now that summer is really here (because it definitely hasn't been sunny and beautiful until this week) what are thoughts on a June/July event? It would be great to have at least a few events through the summer.

Starting in July I'll have access to space we can use on weekends and some weekdays on Lower Queen Anne.

**Comment by blakmatrix** [comment]
What's the size of the space? I'd like to set up last weekend in June on saturday (i.e. June 27th).

**Comment by stuartpb** [comment]
That would conflict with [AngelHack Seattle 2015](http://angelhack.com/hackathon/seattle-2015/).

**Comment by strugee** [comment]
It would also only barely miss OSBRIDGE.

**Comment by sethvincent** [comment]
I'll be out of town on June 27.

Weekends might be kind of hit & miss with things like CascadiaFest, July 4, & other summer activities going on.

It might be good to try a weeknight again. And/or July 18 could be a good Saturday to consider.

**Comment by blakmatrix** [comment]
Closing, Next year we'll have to anticipate the lull, perhaps we can do better next time!
