### ISSUE TITLE
Seattle NodeSchool at Open Project Night

### ISSUE THREAD

**Issue by sethvincent** [nodeschool/seattle#34]
For a while I've been running Open Seattle's (formerly named Code for Seattle) weekly civic hacking night.

Along with renaming to Open Seattle, we're switching up what kinds of events we're holding.

One of the things I'm working on is revising our Civic Hacking Night to become something called Open Project Night.

The general idea is to make our hacking night more open so that we could also include groups like Seattle NodeSchool. Here's a brief description & plan: https://github.com/openseattle/discuss/issues/18

I plan for this event to happen monthly for now, and probably on the 3rd Tuesday of each month.

I think this could be a good supplemental event to regular Seattle NodeSchool events, and would probably only need around 5 volunteers each time.

### Mentors for August 18:
- [x] @sethvincent
- [x] @blakmatrix 
- [x] @noahcollins 
- [x] @brenbob 
- [x] @louisnk 
- [ ]

**Comment by sethvincent** [comment]
I'm setting up this event now and it would be cool to get 3-5 folks interested in mentoring folks who work on NodeSchool workshoppers. It will be a good chance to get a new audience for NodeSchool activities. This first one is at Impact Hub Seattle on August 18. Initial info is up here on the Open Seattle meetup: http://www.meetup.com/openseattle/events/224417379/

**Comment by sethvincent** [comment]
aaaand here's the site for the event series: http://openprojectnight.org/

**Comment by blakmatrix** [comment]
Ahh That sounds excellent! I'd be willing to join the tuesdays ones once in a while, I can make this one. Want me to try and drum up some more support? I'm really busy this week with a release, but I'll try and get something up on the site and meetup.com if you haven't by friday or saturday. I'm guessing will limit the nodeschool crowd to 15-25? what are your thoughts on opening up registration, 2 weeks 10 days, 1 week in advance?

**Comment by sethvincent** [comment]
cool! thanks for making an event on the meetup. help finding a couple more mentors would be nice. there's usually a few experienced javascript/node.js folks at open seattle events anyway.

**Comment by noahcollins** [comment]
I'm available to mentor on the 18th, along with most 3rd Tuesdays. Is there a place I should sign up for that?

**Comment by sethvincent** [comment]
@noahcollins thanks! I edited this issue to add a sign up list and put you on it for the 18th. I'll make issues for the upcoming Tuesday events as well, and you'll be able to sign up by letting us know if you're available in the comments.

**Comment by noahcollins** [comment]
@sethvincent Sounds great! See you on the 18th.

**Comment by brenbob** [comment]
I'm available to mentor on the 18th

**Comment by sethvincent** [comment]
thanks @brenbob!

**Comment by louisnk** [comment]
I'll come help out.

**Comment by ptressel** [comment]
Since this is turning into a NodeSchool event, why not call it that, and have the project night as a separate event?  That would all an alternative to Tuesday, which seems to be the most heavily overbooked Meetup night, at least for tech events.

**Comment by sethvincent** [comment]
@louisnk thanks!

**Comment by sethvincent** [comment]
@ptressel It's definitely not only a a nodeschool event, but a chance to have some cross-organization collaboration. 

It's hard to pick a night that doesn't conflict with something, and the 3rd Tuesday of each month seems pretty good in comparison to others, but this could be reevaluated for upcoming open project nights.

**Comment by ptressel** [comment]
Tuesday, Wednesday, and Thursday are all heavily overbooked.  Friday is a weekend night.  Monday is almost wide open.  There is a weekly PyLadies hack night on Mondays, which draws on the order of 5 people.  That's about it for Mondays.  (Personally, I can't make Tuesday ~ ever, and I don't really want to drop out.)  Why is Monday out of consideration?
