### ISSUE TITLE
Update/Upgrade Site

### ISSUE THREAD

**Issue by blakmatrix** [nodeschool/seattle#35]
For a a while I've been looking at other nodeschool sites and have gotten a lot of good Ideas:
- Become more of a resource to the community by linking to local meetups
- Provide more help via the site for users to get started with NodeSchool
- Perhaps a more dynamic way to list upcomming meetups?
- I really like the completeness of http://nodeschool.io/baltimore/
- http://nodeschool.io/los-angeles/
- http://nodeschool.io/portland-me/
- most used : http://nodeschool.io/sanfrancisco/
- second mosted used : http://nodeschool.io/reno/
## Fun Stuff:

I really like this header effect:
- http://nodeschool.io/dallas/
- http://nodeschool.io/toronto/

could probably make our background emerald colored to fit with seattle (maybe even blue then we got the two colors most seen in Seattle color schemes! 
College Navy Hex Color: #002244; RGB: (0,21,50)
Action Green Hex Color: #69BE28; RGB: (105,190,40)
Wolf Gray Hex Color: #A5ACAF; RGB: (155,161,162) )

**Comment by JustinBeckwith** [comment]
It took a little while, but this is covered in #47 :)
