### ISSUE TITLE
Sunday, August 30, 2015 Call for Mentors

### ISSUE THREAD

**Issue by blakmatrix** [nodeschool/seattle#37]
We have a space for 50 people, from 1:15pm-4:45pm at the Capitol Hil Library, Ideally we'd like to have about a total of 8 volunteers for this event.  If you can commit to this event let us know. I will update this list as we get more mentors.

- [x] Farrin Reid @blakmatrix (Organizer)
- [x] Ava Collins @simplesthing (Organizer - Seattle Ladies JS)
- [x] Seth Vincent @sethvincent (Organizer)
- [x] Stuart P. Bentley @stuartpb (pending)
- [x] Alex Jordan @strugee 
- [x] Josh Benner @libreninja 
- [x] Jessica Wicksnin @jwicksnin  
- [x] Michael Schoonmaker @Schoonology

**Comment by sethvincent** [comment]
i'm in

**Comment by stuartpb** [comment]
Is this rescheduled, or separate, from the 8/18 meetup?

**Comment by stuartpb** [comment]
Also I'm in

**Comment by blakmatrix** [comment]
@stuartpb its a different one

**Comment by strugee** [comment]
I'm in.

**Comment by blakmatrix** [comment]
@stuartpb hows your schedule looking?

**Comment by libreninja** [comment]
Count me in

**Comment by jwicksnin** [comment]
Happy to help mentor if you're still looking for folks!

**Comment by simplesthing** [comment]
@jwicksnin Yes we'd love to have you as a mentor, @blakmatrix can you add, he might need your full as well...

**Comment by louisnk** [comment]
I'll be there.

**Comment by Schoonology** [comment]
I should be available, and would be happy to help. @blakmatrix - what should I look at for expectations, etc.?

**Comment by blakmatrix** [comment]
@Schoonology If you know the core workshoppers on http://nodeschool.io/#workshopper-list you should be good, but at minimum as long as your good with javascript and can help someone find the solutions for themselves with guided debugging, you should be good.

**Comment by huttj** [comment]
If there's room for another mentor, you can count me in.

**Comment by blakmatrix** [comment]
@huttj I think we're good for min reqs, but your welcome to come anyways :)

**Comment by huttj** [comment]
Great! I'll be there! :)

**Comment by sethvincent** [comment]
sidenote: 

for anyone looking for guidance on what's expected of mentors, check this out: [NodeSchool Event Mentor Best Practices Guide](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices)

**Comment by strugee** [comment]
I may be bailing on part or all of this... forgot I have robotics tomorrow :/

Depending on what we're doing I may still make it.

**Comment by strugee** [comment]
Whoops, nevermind... misread the date. See you guys tomorrow.

**Comment by joshgit** [comment]
I'm coming to mentor.

**Comment by sethvincent** [comment]
Aaaahhh, it turns out I can't make it!

**Comment by jwicksnin** [comment]
Just confirming that the location is actually Koru in Queen Anne, no longer
the Cap Hill Library?  See you soon!

**Comment by Schoonology** [comment]
@jwicksnin (and anyone else trying to find the location) - it _is_ at the Koru offices in Lower Queen Anne.

**Comment by stuartpb** [comment]
D'oh - I totally forgot this was today! I should have set a calendar notification for it. Let me see if I can score a ride to assist for the last hour...

**Comment by stuartpb** [comment]
@tiared is coming to pick me up, so it looks like I'll be able to make it for the last half-hour or so. Sorry about that! See #36 for thoughts on how we can avoid this.

**Comment by stuartpb** [comment]
Uh, what's the address? http://www.joinkoru.com/location/seattle dosn't include it.

**Comment by stuartpb** [comment]
Actually, since there's no address and it's not on Google Maps, we can't make it. Sorry.

**Comment by huttj** [comment]
It's on [the meetup page](http://www.meetup.com/Seattle-NodeSchool/events/224548723):

[200 1st Ave W, Seattle, WA](https://www.google.com/maps?f=q&hl=en&q=200+1st+Ave+W,+Seattle,+WA,+us)

**Comment by blakmatrix** [comment]
Thanx to everbody who came!
