### ISSUE TITLE
Call for mentors: September 15 @ Open Project Night

### ISSUE THREAD

**Issue by sethvincent** [nodeschool/seattle#38]
We have a space for about 25 people for NodeSchool, from 5:30 to 8:30 p.m. at Impact Hub Seattle on September 15. 

Volunteers needed: 4-6

If you can commit to this event leave a comment on this issue. 

I'll update this list as we get more mentors.

### Mentors:

- [x] @sethvincent
- [x] @blakmatrix 
- [x] @stuartpb 
- [ ] ?
- [ ] ?
- [ ] ?

Read the [NodeSchool Event Mentor Best Practices Guide](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) before the event.

**Comment by blakmatrix** [comment]
I should be able to make this one

**Comment by sethvincent** [comment]
:+1:

**Comment by stuartpb** [comment]
Okay, next Tuesday, Impact Hub which I know where it is - unlike last time, I should be able to make this one.
