### ISSUE TITLE
Call for mentors: October 20th @ Open Project Night

### ISSUE THREAD

**Issue by blakmatrix** [nodeschool/seattle#39]
We have a space for about 25 people for NodeSchool, from 5:30 to 8:30 p.m. at Startup Hall on October 20th. 

Volunteers needed: 4-6

If you can commit to this event leave a comment on this issue. 

I'll update this list as we get more mentors.

### Mentors:

- [x] @sethvincent
- [x] @blakmatrix 
- [x] @scottnonnenberg 
- [x] @louisnk 
- [x] @huttj 
- [ ] ?

Read the [NodeSchool Event Mentor Best Practices Guide](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) before the event.

**Comment by scottnonnenberg** [comment]
Sign me up for some mentoring! :0)

**Comment by blakmatrix** [comment]
@sethvincent should I consider you not available for these?

**Comment by sethvincent** [comment]
@blakmatrix no i'm generally still available and wander around to see how people are doing.

**Comment by sethvincent** [comment]
This event has switched locations! It will now be at Startup Hall in the University District.

**Comment by sethvincent** [comment]
@scottnonnenberg added you to the list!

**Comment by louisnk** [comment]
I'll be there.

**Comment by huttj** [comment]
I'm down!

**Comment by sethvincent** [comment]
@louisnk, @huttj :+1:
