### ISSUE TITLE
Call for mentors: November 17 @ Open Project Night

### ISSUE THREAD

**Issue by blakmatrix** [nodeschool/seattle#40]
We have a space for about 25 people for NodeSchool, from 5:30 to 8:30 p.m. at Impact Hub Seattle on November 17th. 

Volunteers needed: 4-6

If you can commit to this event leave a comment on this issue. 

I'll update this list as we get more mentors.

### Mentors:

- [x] @sethvincent
- [x] @blakmatrix 
- [ ] ?
- [ ] ?
- [ ] ?
- [ ] ?

Read the [NodeSchool Event Mentor Best Practices Guide](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) before the event.

**Comment by louisnk** [comment]
Won't be in Seattle for this one, sadly.

**Comment by scottnonnenberg** [comment]
The [Node.js meetup](http://www.meetup.com/Seattle-Node-js/events/226175038/) is the same night! That's where I'll be!

**Comment by joshua-gesto** [comment]
The list is so short, this time!

I'll join. :)

**Comment by stuartpb** [comment]
I'll be there - I've been meaning to catch an Open Project Night for a while.
