### ISSUE TITLE
Call for Mentors: December 8 at Moz

### ISSUE THREAD

**Issue by sethvincent** [nodeschool/seattle#41]
We have a NodeSchool Seattle event coming up soon!  6 to 9 p.m. at Moz on Dec. 8. 

Volunteers needed: ~10

If you can commit to this event leave a comment on this issue. 

I'll update this list as we get more mentors.

### Mentors:

- [x] @sethvincent
- [x] @blakmatrix 
- [x] @louisnk
- [x] @joshgit
- [x] @huttj 
- [ ] ?
- [ ] ?
- [ ] ?
- [ ] ?
- [ ] ?

Read the [NodeSchool Event Mentor Best Practices Guide](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) before the event.

**Comment by blakmatrix** [comment]
I'll be there!

**Comment by louisnk** [comment]
I'm in.

**Comment by joshgit** [comment]
I'll be there

**Comment by sethvincent** [comment]
:tada: @blakmatrix @louisnk @joshgit

**Comment by huttj** [comment]
I'll be there!
