### ISSUE TITLE
Recreate the Nodeschool Seattle team

### ISSUE THREAD

**Issue by strugee** [nodeschool/seattle#42]
After the great Nodeschool org deletion of 2015, it'd be great if someone could set up the Seattle team again. I know I mentioned this to someone on seattlehacks a while ago, but presumably they forgot.

(If I'm being 100% honest, I'm mostly suggesting this so I can proudly display my Nodeschool org membership on my profile, infrequently as I actually have time to show up. But whatever.)

**Comment by JustinBeckwith** [comment]
After this week, I'm feeling pretty good about things :)  @satanas, @Xabadu - what do you think?  Can we call this one mission accomplished?

And to @strugee  - we're planning on holding a Seattle NodeSchool on Nov 4th.  Are you interested in joining us as a mentor? Would be awesome to have you!

**Comment by satanas** [comment]
@JustinBeckwith Hell yeah! I'd say we're a team, so mission accomplished :D

**Comment by strugee** [comment]
@JustinBeckwith ughh, I _really_ wish I could! But I just started college so I'm on the other side of the country :(
