### ISSUE TITLE
Nodeschool International Day 21-May 2016

### ISSUE THREAD

**Issue by NorthDecoder** [nodeschool/seattle#43]
Nodeschool International Day on 21-May 2016 is an
ad hoc celebration of all things nodejs.  I thought
it would be a good idea for me to volunteer
as the timezone coordinator.

I am writing to see if Tacoma-JS can collaborate 
somehow that day via video chat and gitter with your
group for some part of the time from 0830-1200 PST
following the guidelines at [:link:](http://nodeschool.io/international-day).

I can be reached at:
  http://www.meetup.com/Tacoma-JS/events/226412924/
  https://github.com/NorthDecoder

**Comment by JustinBeckwith** [comment]
Apologies we missed this!  We're bootstrapping the NodeSchool Seattle team again, so in the future we'll be a little more responsive.
