### ISSUE TITLE
Improvements to https://nodeschool.io/seattle

### ISSUE THREAD

**Issue by satanas** [nodeschool/seattle#46]
This must include:
* Style
* Content updates
* Code of conduct

**Comment by JustinBeckwith** [comment]
Looks to be covered in #47.  Just need to figure out how to publish  😂  I don't have admin rights on the repo, so I can't poke about in the github pages settings.  @satanas it would be rad if I could have admin, or if you could take a look.

**Comment by satanas** [comment]
No problem, I don't have admin either but I'll take a look 👍

**Comment by Xabadu** [comment]
Hey @JustinBeckwith @satanas site is published now! Sorry for not providing all the instructions :( 

The GitHub pages part must use the master branch/docs option (I just created the master branch in this repo and made the change). You shouldn't have any more problems going forward.

**Comment by Xabadu** [comment]
Oh, btw, I added you guys as admin to the repo 🤘

**Comment by JustinBeckwith** [comment]
Thank you @Xabadu!

**Comment by satanas** [comment]
Awesome! Thanks @Xabadu.

And just for the record, from now on we should send the PRs against `master` instead of `gh-pages` 😉
