### ISSUE TITLE
Mentor Registration for November 4th, 2017

### ISSUE THREAD

**Issue by JustinBeckwith** [nodeschool/seattle#48]
Greetings folks! 
Google is hosting the next NodeSchool Seattle at the [Google Fremont office](https://www.google.com/maps/place/Google+Seattle/@47.6493009,-122.3527234,17z/data=!3m1!4b1!4m5!3m4!1s0x54901506e4e1c263:0x79576ab382d8ddaa!8m2!3d47.6492973!4d-122.3505347) on November 4th, from 1 PM - 5 PM.  You can join the [Meetup as a learner here](https://www.meetup.com/Seattle-NodeSchool/events/244074620/)!

We are looking for mentors.  If you would like to join us and other passionate folks, mentors should:
- Have already completed the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event.
  - Having also completed elective workshoppers is a great bonus.
- Review the [Mentor Best Practices wiki page](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices).
- Arrive 30 minutes early (12:30p) so we can get setup and have our mentor meeting.

Confirmed mentors:
- [x] @JustinBeckwith
- [x] @ace-n 
- [x] @libreninja 
- [x] @Rob-ot 
- [x] @sharpstef 
- [x] @stuartpb 

To sign up as a mentor - just leave a comment!

**Comment by JustinBeckwith** [comment]
@CADBOT @satanas @Xabadu

**Comment by libreninja** [comment]
I'll be there

**Comment by ace-n** [comment]
Not on the Meetup yet, but will be mentoring.

**Comment by Rob-ot** [comment]
Sign me up as a mentor!

**Comment by stuartpb** [comment]
I'll go ahead and complete those core workshoppers, then you can count me in for the 4th.

**Comment by sharpstef** [comment]
I have to complete the workshoppers, but I'll get them done and be there.

**Comment by JustinBeckwith** [comment]
Greetings folks!  Thanks for signing up to mentor nodeschool  👏👏👏   The event starts at 1:00 PM in Fremont, and I plan on being there around noon.  It would be awesome if a few others could come from 12-12:30 to help with set up, and making sure we have a good plan.  

Looking forward to seeing everyone!

**Comment by stuartpb** [comment]
Could you make sure I'm on the checklist?

**Comment by JustinBeckwith** [comment]
Hey y'all - I'm in the building and setting up.  If you have any questions, feel free to DM me on the twitter, I'm @JustinBeckwith

**Comment by JustinBeckwith** [comment]
Thanks for the help everyone!  This went fantastic, and we couldn't have done it without y'all.
