### ISSUE TITLE
Twitter credentials for @nodeschool_sea

### ISSUE THREAD

**Issue by satanas** [nodeschool/seattle#49]
Hey @blakmatrix, we're reviving the NodeSchool Seattle and @sethvincent told me you created the Twitter account (@nodeschool_sea). Our next event is on Nov 4th and we'd like to start promoting it on Twitter, however, none of us have access to @nodeschool_sea to start tweeting.

Could you send us a private email to @JustinBeckwith, @sethvincent, @CADBOT (charliec364 at gmail.com) and me with the credentials of that account?

Thanks a lot!

**Comment by satanas** [comment]
@blakmatrix Ping!

**Comment by blakmatrix** [comment]
I completed what was asked, this is ready to be closed.

**Comment by JustinBeckwith** [comment]
Thanks!
