### ISSUE TITLE
Task to create github issue for mentor registration

### ISSUE THREAD

**Issue by satanas** [nodeschool/seattle#50]
Oakland folks have pretty much everything automated, and it would be nice if we can do the same. So let's build a task that let us create the github issue for mentor registration. We can get an idea of what to do [here](https://github.com/nodeschool/oakland/blob/master/scripts/create.js#L135-L166).

**Comment by e-e** [comment]
@satanas It looks like the ```scripts/create.js``` script that oakland is using seems to do what this (#50), #52, #53, and #54 are outlining. Do you want these to each be individual tasks/scripts? Or can we just take their script and swap in the Seattle info?

**Comment by satanas** [comment]
@e-e More than individual scripts I was thinking about having the same script but starting with the bare minimum (like a template) and then progressively adding all the tasks we need to it, that way we can split the work into smaller chunks (most of all have only a few hours a week to contribute). Basically, that's why I split the tasks into different tickets. But yes, you can totally do all them in one go if you want :)

**Comment by e-e** [comment]
@satanas ok cool. i just need to finish figuring out / testing the meetup event stuff. should be done sometime this week.

**Comment by e-e** [comment]
@satanas @stuartpb This is pretty much finished, but I am stuck on testing on meetup. There is a group dedicated to testing, but you need to be added as a coordinator, and no one has gotten back to me yet. I created a group to test with, which worked for one night, and then they (meetup) deleted it the next morning because it wasn't a real group. I opened a ticket with meetup explaining the situation, but have yet to hear from them. Any suggestions for how to test this script? Everything else with posting to meetup up works correctly - the only thing I haven't gotten to work is getting the latitude/longitude to stick, so it ends up not having a location set for the event.

**Comment by stuartpb** [comment]
Can you create a second test group for the duration of your second test (then delete it until you need to test again)?

**Comment by e-e** [comment]
@stuartpb I could, but it is $15 every time, so ideally I would like to find some other solution. That is an option though.

**Comment by stuartpb** [comment]
So they deleted your test group, but they *kept* the $15 you spent to create it? That's messed up, and if that's the case, I definitely wouldn't go any further without hearing from Meetup Support.

Have you reached out to be added as an organizer to the [Meetup API Testing Sandbox group](https://www.meetup.com/Meetup-API-Testing/)?

**Comment by e-e** [comment]
I just looked at the email again, and they are refunding the $15. So I could give that a try again. As for the sandbox group, I've sent a couple of messages in the last 4-5 days, but haven't gotten any sort of response.

**Comment by satanas** [comment]
@e-e Is your email address god@eric.wtf? I entered the sandbox group and seems like I can send invitations (maybe because I'm a coordinator, I don't know), so I just sent you one. If that is not your email, please give me the real one to try again.

**Comment by e-e** [comment]
@satanas i think the email that is registered on meetup is ellingsonster@gmail.com, but i can just create a new account with the email you used. thanks!

**Comment by e-e** [comment]
@satanas well that's the thing. I joined the group, but that doesn't give me access to post new events. I'm waiting on one of the coordinators to give me that access, but I haven't heard back from anyone yet. I think I'm just going to create another test group, and hopefully get it figured out before they shut it down.
