### ISSUE TITLE
Mentor Registration for December 2nd, 2017

### ISSUE THREAD

**Issue by satanas** [nodeschool/seattle#57]
Hello folks!

Groupon is hosting the next NodeSchool Seattle at the [Groupon office](https://goo.gl/maps/fJAN87K4Tjz) on December 2nd, from 1:00 PM - 5:00 PM (you can sign up as a learner [here](https://www.meetup.com/Seattle-NodeSchool/events/245316852/)).

We are looking for mentors. If you would like to join us and other passionate folks, you should:
- Have already completed the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event.
  - Having also completed elective workshoppers is a great bonus.
- Review the [Mentor Best Practices wiki page](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices).
- Arrive 30 minutes early (12:30 PM) so we can set up and have our mentor meeting.

Confirmed mentors:
- [x] @satanas
- [x] @stuartpb
- [x] @melissajimison
- [x] @kevjames3 

To sign up as a mentor just leave a comment!

**Comment by stuartpb** [comment]
Ooh, downtown, nice! I'm in.

**Comment by kevjames3** [comment]
I am in

**Comment by satanas** [comment]
Howdy, folks! First of all, thanks for signing up to mentor in the NodeSchool Seattle. The event starts at 1:00 PM in at the [Groupon office in downtown](https://goo.gl/maps/fJAN87K4Tjz) (1201 3rd Ave) and it would be great if you could come around 12:30 PM to do a quick check-in before the event.

There will be a meeting point in the entrance of the building where we (grouponers) will pick you up
and take you to the office. Please, don't hesitate to send me a DM on Twitter ([@satanas82](https://twitter.com/satanas82)) if you have any question or concern.

Looking forward to seeing you tomorrow!

**Comment by satanas** [comment]
Thank you to all the mentors who participated in the last NodeSchool! It went great thanks to your support. I hope to see you in the next one ;)
