### ISSUE TITLE
Feb 28th, 2015 Event Curriculum 

### ISSUE THREAD

**Issue by blakmatrix** [nodeschool/seattle#6]
Since we are having such a large audience (~100) this time around, I think we should pick some curriculums/workshops to focus on

Insight: Noticing other nodeschools, I've been seeing that some people in beginner workshops generally get to about 1-2 more successive workshops in 2-3 hours. I don't want us to get overwhelmed but I'd like for us to plan for providing enough content to last the 3-4 hours we have available to us. 

My ideas are:
* choose 3-4 to have ready at the event
* choose a path with a 2-3 focused workshops and *loosely based mentor assignment*
  * Beginners
  * Intermediate
  * Advanced?

What do others think?

**Comment by YonasBerhe** [comment]
Would each mentor choose between beginners, Intermidiate, and Advanced to focus on for the last three hours?
