### ISSUE TITLE
Mentor Registration for July 14th, 2018

### ISSUE THREAD

**Issue by satanas** [nodeschool/seattle#66]
Hello folks!

Groupon is hosting the next NodeSchool Seattle at **Groupon** on **July 14th, from 1:00PM-5:00PM** (you can sign up as a learner [here](https:&#x2F;&#x2F;www.meetup.com&#x2F;Seattle-NodeSchool&#x2F;events&#x2F;252142235&#x2F;)).

-----

We are looking for mentors. If you would like to join us and other passionate folks, you should:

- Have already completed the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event.
  - Having also completed elective workshoppers is a great bonus.
- Review the [Mentor Best Practices wiki page](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices).
- Arrive 30 minutes early (12:30PM) so we can set up and have our mentor meeting.

#### Confirmed mentors:

- [x] @satanas
- [x] @geppy 
- [x] @ingoclaro
- [x] @melissajimison 
- [x] @noansknv 

To sign up as a mentor just leave a comment!

**Comment by geppy** [comment]
I'm interested in mentoring.

**Comment by satanas** [comment]
@geppy Added to the list! :)

**Comment by ingoclaro** [comment]
@satanas sign me up as a mentor

**Comment by satanas** [comment]
@ingoclaro yay! done :)

**Comment by melissajimison** [comment]
@satanas sign me up as a mentor

**Comment by satanas** [comment]
@melissajimison wohoo! Added ;)

**Comment by satanas** [comment]
@noansknv hell yeah!

**Comment by geppy** [comment]
@satanas I can't make it.

**Comment by satanas** [comment]
@geppy aww. Well, see you next time!

**Comment by satanas** [comment]
Hello, guys! First of all, thank you so much for signing up as mentors for the NodeSchool Seattle. As you may know, the event starts at 1:00 PM at the Groupon's office in the 28th floor (Rainy With A Chance Of Rain) but it would be great if you could come around 12:30 PM to do a quick check-in before the event.

Since all of you are grouponers, remember to bring your badge to enter because the building is closed on Saturdays ;)

See you later!

**Comment by ingoclaro** [comment]
I'm here already!

**Comment by satanas** [comment]
@melissajimison @noansknv @ingoclaro Thank you so much for being awesome mentors yesterday! You guys rock and this event wouldn't be the same without you. Hope to see you next time :)
