### ISSUE TITLE
Location for July 14th, 2018

### ISSUE THREAD

**Issue by geppy** [nodeschool/seattle#69]
The [event page on Meetup](https://www.meetup.com/Seattle-NodeSchool/events/252142235/) doesn't have a location set.

The description mentions a location (Groupon, 1201 3rd Ave, Seattle, WA 98101), but that doesn't show up in contexts like calendar export and the event details infobox.

**Comment by satanas** [comment]
Hi @geppy, I have added the location to the meetup event. Thanks for reporting the issue 👍
