### ISSUE TITLE
Feb 28th, 2015 Call for Mentors

### ISSUE THREAD

**Issue by blakmatrix** [nodeschool/seattle#7]
We will need about 20 mentors for this event. If you can commit to Feb. 28th, 2015 from 1-5pm let us know. I will update this list as we get more mentors.

- [x] Farrin Reid @blakmatrix / Organizer
- [x] Seth Vincent @sethvincent / Organizer
- [x] Will Scott @willscott 
- [x] Yonas Berhe @YonasBerhe 
- [x] Rob Middleton @Rob-ot 
- [x] Gary Anderson @saasmath 
- [x] Louis K @louisnk 
- [x] PJ Briggs @pjbr
- [x] Josh Benner @sjbenner  
- [x] Alex Jordan @strugee  
- [x] David Harris @RnbWd 
- [x] Eugene Kalinin @eugeniy 
- [x] Craig Beck @craigbeck   
- [x] Andrew Gall @housepage 
- [x] Scott Brady @scottbrady  
- [ ] ? 
- [ ] ? 
- [ ] ? 
- [ ] ? 
- [ ] ? 
- [ ] ? 
- [ ] ?

**Comment by willscott** [comment]
I can help

**Comment by YonasBerhe** [comment]
I'm down

**Comment by Rob-ot** [comment]
I'm in!

**Comment by saasmath** [comment]
I can help on this.  My current high school software students have completed the Javascrpting module, and some have started on learnyounode.  I will also let them know of the event.

**Comment by KatieK2** [comment]
Wish I were free for this. Alas, my weekends always book up pretty quickly.

**Comment by blakmatrix** [comment]
@KatieK2 that's alright I appreciate the thought.

I was throwing around some ideas of smaller nodeschool events possibly during different times. I was thinking of opening a thread seeing what peoples interest were after this February event, so keep an eye out!

**Comment by louisnk** [comment]
I'm in.

**Comment by sjbenner** [comment]
Please add me to the list!

**Comment by blakmatrix** [comment]
Awesome, Thanks to everyone for signing up, If anyone knows a friend that would be down to be a mentor, lease reach out to them, as it is now it'll be a 10:1 student to mentor ratio. We'd like to see 5:1 for optimal effectiveness.

Thanks everyone, I can't wait!

**Comment by strugee** [comment]
I can help out with this (although I only know core Node; I'm not too familiar with e.g. Express).

**Comment by sethvincent** [comment]
hey @housepage, this is what I was talking about earlier today.

I plan on being prepared to help people with these tutorials:
- [javascripting](https://github.com/sethvincent/javascripting)
- [learnyounode](https://github.com/rvagg/learnyounode)
- [how-to-npm](https://github.com/npm/how-to-npm)
- [stream-adventure](https://github.com/substack/stream-adventure)

You can see all the tutorials here: http://nodeschool.io/#workshoppers

This is the meetup page for the event: http://www.meetup.com/Seattle-NodeSchool/events/220020622/

**Comment by RnbWd** [comment]
I'd like to be a mentor!!

**Comment by craigbeck** [comment]
Sign me up.

**Comment by blakmatrix** [comment]
@all I hope all of you are just as exited as I am about tommorow's event, We still need more mentors, if you could retweet https://twitter.com/blakmatrix/status/571429823513366529 and ask anybody you know, that'd be awesome as we are still looking to get 9 more mentors. I will update this thread with directions and info later today for the mentors and the event in general.

**Comment by housepage** [comment]
Sign me up!

**Comment by blakmatrix** [comment]
Location

Where: 1633 Westlake Avenue North, Suite 400, Seattle, WA 98109
When: 1pm-4pm February 28th, 2015 **(Mentors should arrive 30 minutes early for setup/discussion)**
Parking: If guest parking is taken, there is paid parking down 8th Avenue North, in the SRM building, located at 1505 Westlake Ave North (where Westlake Ave. N. and 8th Ave. N. meet)
Arrival: There are two entrances 1633 Westlake Avenue North or 1616 8th Avenue North, If you are driving, use the 8th Avenue North garage entrance (it is a brick building with the parking entrance unmarked on the south end of the building) for guest parking if available.
If you are arriving by taxi or public transportation, you can enter the building from either entrance, but the 8th Ave. N. entrance is more suitable for passenger load/unload.

I've asked attendies to prepare by installing these core workshops:
`npm install -g learnyounode`
`npm install -g javascripting`
`npm install -g git-it`
`npm install -g how-to-npm`
`npm install -g stream-adventure`

**Please bring some USB thumb drives if you have any to spare** -- incase the internet is slow we can use them to get around that.
**Please try and work through these core workshops so you can provide more help onsite.**
Also checkout this thread: https://github.com/nodeschool/organizers/issues/97

**Comment by blakmatrix** [comment]
Also, If all the mentors could move to the waitlist/no it'll help move some of the wait listed people up. (wish there was a better way to do this)

**Comment by scottbrady** [comment]
I'm happy to help out as a mentor. I'm new to nodeschool but I'll try to take a look at a few tutorials.

**Comment by blakmatrix** [comment]
**Thank you all** for helping out during todays Event! Pat yourselves on the shoulder for making this event happen! If You wouldn't mind, please comment on how the event went-- What went well, what could go better, any flags, how the workshoppers went, etc. here:  https://github.com/nodeschool/seattle/issues/10
Farrin Reid @blakmatrix / Organizer
Seth Vincent @sethvincent / Organizer
Will Scott @willscott
Yonas Berhe @YonasBerhe
Rob Middleton @Rob-ot
Gary Anderson @saasmath
Louis K @louisnk
PJ Briggs @pjbr
Josh Benner @sjbenner
Alex Jordan @strugee
David Harris @RnbWd
Eugene Kalinin @eugeniy
Craig Beck @craigbeck
Andrew Gall @housepage
Scott Brady @scottbrady

**Comment by sethvincent** [comment]
Hey folks that mentored at the February event! There's a call for mentors for the March 28 event here: https://github.com/nodeschool/seattle/issues/13
