### ISSUE TITLE
Mentor Registration: NodeSchool Seattle - September 2018 at Groupon, Inc.

### ISSUE THREAD

**Issue by satanas** [nodeschool/seattle#72]
Hello folks!

Groupon is hosting the next NodeSchool Seattle at **Groupon, Inc.** on **September 29th, from 1:00PM-5:00PM** (you can sign up as a learner [here](https:&#x2F;&#x2F;www.meetup.com&#x2F;Seattle-NodeSchool&#x2F;events&#x2F;254805374&#x2F;)).

-----

We are looking for mentors. If you would like to join us and other passionate folks, you should:

- Have already completed the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event.
  - Having also completed elective workshoppers is a great bonus.
- Review the [Mentor Best Practices wiki page](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices).
- Arrive 30 minutes early (12:30PM) so we can set up and have our mentor meeting.

#### Confirmed mentors:

- [x] @satanas
- [x] @jayhatha
- [x] @melissajimison 
- [x] @moonpatroller 
- [x] @ianfoo 

To sign up as a mentor just leave a comment!

**Comment by jayhatha** [comment]
Hey, I'd love to sign up as a mentor!

**Comment by satanas** [comment]
@jayhatha Yay! Added 👍

**Comment by melissajimison** [comment]
@satanas Please sign up as a mentor!

**Comment by satanas** [comment]
@melissajimison hell yeah!

**Comment by moonpatroller** [comment]
@satanas Please sign up as a mentor!

**Comment by satanas** [comment]
Hello, all! First, thank you so much for signing up as mentors for the September edition of NodeSchool Seattle.

As you may know, the event starts at 1:00 PM at the [Groupon's office](https://www.google.com/maps/search/?api=1&query=1201+Third+Ave+Suite+2800%2C+Seattle%2C+WA%2C+us) but it would be great if you could come around 12:30 PM to do a quick check-in before the event.

Just so you know, the building is closed on Saturdays so there will be a meeting point in the entrance on 3rd ave where you must wait until a grouponer picks you up and takes you to the office. If you come and there's no one around, feel free to ping me [@satanas82](https://twitter.com/satanas82) or [@andrearrs](https://twitter.com/andrearrs) on Twitter and we will get you.

See you tomorrow!

**Comment by ianfoo** [comment]
It looks like you're well covered (and it's under 12 hours until the event), but if any additional mentor coverage is desired, I'm up for it. I haven't been primarily a JS dev for a while, but having attended the April event, I had a nice time and was able to offer help to those perhaps less experienced.

**Comment by satanas** [comment]
Hey @ianfoo, mentors are always welcome! So, see you tomorrow 😄

**Comment by satanas** [comment]
@ianfoo @moonpatroller @jayhatha Thank you guys for your great job as mentors yesterday! It's cool to see new faces along with returning faces. Hopefully, we'll meet again in December.

Please, feel free to send me any feedback you may have about how can we improve the event and make it better for everyone. I'd really appreciate it.

Cheers and thanks again! 🎉

**Comment by moonpatroller** [comment]
The breadsticks were lit.

**Comment by satanas** [comment]
@moonpatroller Hahaha, cool! I'll order more for the next event 😉
