### ISSUE TITLE
Mentor registration for March 9th, 2019

### ISSUE THREAD

**Issue by satanas** [nodeschool/seattle#79]
Hello folks!

Groupon is hosting the next NodeSchool Seattle at **Groupon, Inc.** on **March 9th, from 1:00PM-5:00PM** (you can sign up as a learner [here](https://www.meetup.com/Seattle-NodeSchool/events/259302922/).

-----

We are looking for mentors. If you would like to join us and other passionate folks, you should:

- Have already completed the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event.
  - Having also completed elective workshoppers is a great bonus.
- Review the [Mentor Best Practices wiki page](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices).
- Arrive 30 minutes early (12:30PM) so we can set up and have our mentor meeting.

#### Confirmed mentors:

- [x] @satanas
- [x] @ianfoo 
- [x] @cbenv 
- [x] @zhoutwo 
- [x] @kevjames3 

To sign up as a mentor just leave a comment and I'll add you to the list!

**Comment by ianfoo** [comment]
Hey Wil, looking forward to it and happy to help however I can.

**Comment by satanas** [comment]
@ianfoo
![](https://media3.giphy.com/media/K4EkrpzHJmZFu/giphy.gif?cid=3640f6095c75dcf0382e464a45538e81)

**Comment by cbenv** [comment]
I am in!

**Comment by zhoutwo** [comment]
I'd be happy to help out as a mentor too

**Comment by satanas** [comment]
@cbenv 
![](https://media3.giphy.com/media/14Xx5B178hibS/giphy.gif?cid=3640f6095c76ee196e556c6f2e2a1da7)

**Comment by satanas** [comment]
@zhoutwo 
![](https://media.giphy.com/media/l2YWCPLrCIaNc9QT6/giphy.gif)

**Comment by kevjames3** [comment]
I will be there as a mentor

**Comment by satanas** [comment]
@kevjames3 
![](https://media3.giphy.com/media/3o6UB3VhArvomJHtdK/giphy.gif?cid=3640f6095c7f294f6e49524e4d1352de)

**Comment by satanas** [comment]
Hello everyone! Thanks for signing up as mentors for tomorrow's NodeSchool. Remember to arrive 30 minutes early (12:30PM) so we can set up and have our mentors meeting before the event starts.

See you all tomorrow! 🎉

**Comment by satanas** [comment]
Thank you guys for mentoring today, you did a great job! See you in the next workshop 🤘 

![](https://media3.giphy.com/media/JVdF14CQQH7gs/giphy.gif?cid=3640f6095c8496ab6b4a6834416e5ce6)
