### ISSUE TITLE
NodeSchool International Day

### ISSUE THREAD

**Issue by blakmatrix** [nodeschool/seattle#8]
We are excited to announce that May 23rd, 2015 is the first NodeSchool International Day, a day of coordinated NodeSchool events around the globe.

**Comment by sethvincent** [comment]
:tada: :pizza: :cake:

**Comment by blakmatrix** [comment]
I am asking IMS Health if they will sponsor the space for this day.

**Comment by keithjia** [comment]
Great!

and a more selfish thought, what about a location on the eastside? we might
draw different crowd and mix it up...

On Thu, Apr 16, 2015 at 10:36 AM, Farrin Reid <notifications@github.com>
wrote:

> I am asking IMS Health if they will sponsor the space for this day.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodeschool/seattle/issues/8#issuecomment-93792777>.
>



-- 
Keith Jia
(310) 408 9637 Cell

**Comment by blakmatrix** [comment]
Woot We are confirmed for space!

**Comment by louisnk** [comment]
IMS Health? Sad that I won't be there for this one!

On Mon, Apr 20, 2015 at 5:35 PM, Farrin Reid <notifications@github.com>
wrote:

> Woot We are confirmed for space!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodeschool/seattle/issues/8#issuecomment-94599915>.
>



-- 
- Louis Kinley
Seattle NodeSchool <http://nodeschool.io/seattle> Organizer | Seattle
CoderDojo <http://seattlecoderdojo.com> Mentor | @louisnk
<http://twitter.com/louisnk>
425 442 6481
