### ISSUE TITLE
Mentor Registration for May 4th, 2019

### ISSUE THREAD

**Issue by satanas** [nodeschool/seattle#83]
Hello folks!

Groupon is hosting the next NodeSchool Seattle at **Groupon Seattle** on **May 4th, from 1:00PM-5:00PM** (you can sign up as a learner [here](https:&#x2F;&#x2F;www.meetup.com&#x2F;Seattle-NodeSchool&#x2F;events&#x2F;260553626&#x2F;)).

-----

We are looking for mentors. If you would like to join us and other passionate folks, you should:

- Have already completed the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event.
  - Having also completed elective workshoppers is a great bonus.
- Review the [Mentor Best Practices wiki page](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices).
- Arrive 30 minutes early (12:30PM) so we can set up and have our mentor meeting.

#### Confirmed mentors:

- [x] @satanas
- [x] @ianfoo
- [x] @ginog
- [x] @nephenthe
- [x] @moonpatroller

To sign up as a mentor just leave a comment!

**Comment by ianfoo** [comment]
Hey Wil! I'll be there. If there's a link for the focused curriculum that I can use to prepare for that, please send it along.

**Comment by satanas** [comment]
![](https://media2.giphy.com/media/cEYFeDB8PpXqYekMuPK/giphy.gif?cid=790b76115cbf5c33674a6a7645e4212c)

@ianfoo I'll send the details in the next few days, stay tuned!

**Comment by ginog** [comment]
I can be there for some basic help.  :p

**Comment by satanas** [comment]
@ginog 
![](https://media2.giphy.com/media/l2JIjCKbr7TlzZuUg/giphy.gif?cid=790b76115cccb3d75a64354f7759b055&rid=giphy.gif)

BTW @ianfoo, here is what I'll be using for the focused session https://github.com/satanas/nodeschool-session-api-node. Still working on some details with the README but the code it's mostly completed. Feel free to drop comments/suggestions 😉

**Comment by nephenthe** [comment]
I'll be there!

**Comment by satanas** [comment]
@nephenthe Added!
![](https://media3.giphy.com/media/VZgFs8Vovok5a/giphy.gif?cid=790b76115cccb4ec39623548452d37ea&rid=giphy.gif)

**Comment by moonpatroller** [comment]
Please add me.

**Comment by satanas** [comment]
@moonpatroller added!
![](https://media1.giphy.com/media/5wWf7H0WTquIU1DFY4g/giphy.gif?cid=790b76115ccdd0d2765a7375630dd62e&rid=giphy.gif)

**Comment by satanas** [comment]
@ianfoo @ginog @nephenthe @moonpatroller Thank you guys for being such amazing mentors! See you next time 🙌
