### ISSUE TITLE
Security vulnerabilities to be addressed

### ISSUE THREAD

**Issue by keywordnew** [nodeschool/seattle#86]
There are a few security vulnerabilities in dependencies used by this repo.

Would y'all have access to the Alerts feature?

<img width="744" alt="Screen Shot 2019-05-04 at 8 40 22 PM" src="https://user-images.githubusercontent.com/10335475/57188031-e52ef180-6eac-11e9-81f8-2da4aa683b1b.png">

The above packages need to be updated and changes to `package.json` committed.

https://github.com/nodeschool/seattle/network/alerts

**Comment by satanas** [comment]
Hey @keywordnew, I have access to the Alerts feature. Would you like to contribute to fixing some of those vulnerabilities?

**Comment by keywordnew** [comment]
I think this could be great one for a `good first issue` label :)

**Comment by keywordnew** [comment]
This looks resolved. Closing for now, please feel free to reopen at any time :)
