### ISSUE TITLE
Mentor Registration for June 1st, 2019

### ISSUE THREAD

**Issue by satanas** [nodeschool/seattle#87]
Hello folks!

Microsoft is hosting the next NodeSchool Seattle at **Microsoft Reactor** (Microsoft Building 20) at [3709 157th Ave NE, Redmond, WA 98052](https://www.google.com/maps/place/3709+157th+Ave+NE,+Redmond,+WA+98052/@47.6436745,-122.1332843,17z/data=!3m1!4b1!4m5!3m4!1s0x54906d71fad78e11:0x41c6b1be983cf409!8m2!3d47.6436745!4d-122.1310903) on **June 1st, from 1:00PM-5:00PM**.

-----

We are looking for mentors. If you would like to join us and other passionate folks, you should:

- Have already completed the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event.
  - Having also completed elective workshoppers is a great bonus.
- Review the [Mentor Best Practices wiki page](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices).
- Arrive 30 minutes early (12:30PM) so we can set up and have our mentor meeting.

#### Confirmed mentors:

- [x] @satanas
- [x] @ianfoo
- [x] @btholt
- [x] @fiveisprime

To sign up as a mentor just leave a comment!

**Comment by ianfoo** [comment]
👋

**Comment by satanas** [comment]
@ianfoo Yesssss!
![](https://media0.giphy.com/media/wrzf9P70YWLJK/giphy.gif?cid=790b76115cd5b5aa7748683141f794ec&rid=giphy.gif)

**Comment by btholt** [comment]
Count me in!

**Comment by fiveisprime** [comment]
I'm in for mentoring!

**Comment by satanas** [comment]
@btholt 
![](https://media.giphy.com/media/tIeCLkB8geYtW/giphy.gif)

**Comment by satanas** [comment]
@fiveisprime
![](https://i.giphy.com/media/tCV2LrPPYfqCY/giphy.webp)

**Comment by satanas** [comment]
Thank you guys for joining us! And great presentation from @btholt! 👏 👏 👏 

Hope to see you again next time!
