### ISSUE TITLE
Mentor Registration for August 17th, 2019

### ISSUE THREAD

**Issue by satanas** [nodeschool/seattle#88]
Hello folks!

Groupon is hosting the next NodeSchool Seattle at **Groupon** on **August 17th, from 1:00PM-5:00PM** (you can sign up as a learner [here]()).

-----

We are looking for mentors. If you would like to join us and other passionate folks, you should:

- Have already completed the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event.
  - Having also completed elective workshoppers is a great bonus.
- Review the [Mentor Best Practices wiki page](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices).
- Arrive 30 minutes early (12:30PM) so we can set up and have our mentor meeting.

#### Confirmed mentors:

- [x] @satanas
- [x] @ianfoo
- [x] @enkil2003
- [ ] You???

To sign up as a mentor just leave a comment!

**Comment by ianfoo** [comment]
👋 I'm in!

**Comment by satanas** [comment]
@ianfoo 
![](https://media.giphy.com/media/d4blihcFNkwE3fEI/giphy.gif)

**Comment by enkil2003** [comment]
I'm in as mentor too.

**Comment by satanas** [comment]
@enkil2003 
![](https://media0.giphy.com/media/hVYVYZZBgF50k/giphy.gif?cid=790b76112594056ca7c8f957833ee495745626991dc71c5a&rid=giphy.gif)

**Comment by moonpatroller** [comment]
I'd like to mentor

**Comment by satanas** [comment]
Thank you so much guys for being amazing mentors!
![](https://media1.giphy.com/media/vCKC987OpQAco/giphy.gif?cid=790b761192af40fe4747213deb31ee91e7ed482aecd273b5&rid=giphy.gif)

P.S: @moonpatroller sorry that I didn't catch your message on time. Next time I'll check an hour before the event but feel free to reach out to me directly when arriving at the workshop if I haven't replied back with a gif 😄
